---
title: "HW 3"
author: "Ericka Griggs"
date: '2023-02-01'
output: html_document
---

## HW 3

1.`[ \t]{2,}`   replace ','
This statement is saying find the spaces and then two characters with a , after it and to replace all that with just a `


2.`(\w+), (\w+), (.*)`  replace `\2 \1 \(\3\)`
This statement is defining one or more objects as one or more characters and then reordering the objects.


3.`(\d{4}.)` replace `\n\1`
This statement is defining digits by 4 and then adding a line break before each 4 digit code.


4.`(\d{4}) (\w+\s*\w+\s*)*` replace `\2_\1`
This statement is redefining object and then adding the song title and then changing the order and added an underscore. 


5.`(\w)\w+,(\w+),(\d+.\d+),(\d+)` replace `\1_\2,\4`
This statement first defines 4 objects, 1st letter of first word, entire second word, and then all the numbers in the statement. It then replaces the statement with just the first letter of the first word, followed by an underscore, and with the fourth object of just the last digits.


6.`(\w{6})(\w+),(\d+)` replace `\1,\3`
This statement redefined the object as the first four letters of the word then replacing it with a shortened word.

7.`(\w{3})\w+,(\w{3})\w+,(\d+.\d+),(\d+)` replace `\1\2,\4,\3` 
This statement redefines the objects as the first three letters of word one, then the first three letters of word two, followed by the digits as two separate objects. The replacement is just the first three letters of word one and two and then the digits rearranged in their order. 