---
title: "HW 4"
author: "Ericka Griggs"
date: '2023-02-08'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1
```{r}
# assigning values to variables
x <- 1.1
a <- 2.2
b <- 3.3

# a using variables in equation
z <- x^a^b
print(z)
# b using variables in different equations
z <- (x^a)^b
print(z)
# c using variables in another equations
z <- 3*x^3 + 2*x^2 + 1
print(z)

```



## Question 2

```{r}
# a created a sequence forward and backward
z<-c(seq(1,8),seq(7,1))
print(z)
```

   ```{r}
# b created a sequence that repeats every # the amount of times that # equals
rep(1:5, c(1,2,3,4,5))
```

  ```{r}
# c same as b but in reverse
rep(5:1, c(1,2,3,4,5))
```

## Question 3

  ```{r}
# asked for two numbers that can be found up to 100
z <- runif(2, max = 100)
print(z)
# assigned one of the numbers to x
x <- 66.17
print(x)
# assigned one of the numbers to y
y<-63.75
print(y)
# used the vairables for x and y to solve for the polar coordinates
polcor <- c(sqrt(x^2+y^2),atan(y/x))
print(polcor)
```


## Question 4 

```{r}
# created queue as a variable and combined the animal names
queue <- c("sheep", "fox", "owl", "ant")
print(queue)
# added serpent
queue <- append(queue,"serpent")
queue <- c(queue[2:5])
print(queue)
# added donkey to front of line
queue <- append("donkey",queue)
print(queue)
# removed serpent
queue <-c(queue[1:4])
print(queue)
# removed owl
queue <- c(queue[1],queue[2],queue[4])
print(queue)
# added aphid in front of ant
queue <- c(queue[1:2],"aphid", "ant")
print(queue)
# asked where in the variable of queue is aphid
which(queue == "aphid")
```




## Question 5

```{r}
# this is asking that for a variable from 1-100 if it is divisible by 7 or 3 or 2 print the variables
for(x in 1:100)
  if(! x%%7 == 0)
    if(! x%%3 == 0)
      if(!x%%2==0)
print(x)
```

