---
title: "HW7"
author: "Ericka Griggs"
date: '2023-03-22'
output: html_document
---

# 1 
```{r,warning=FALSE,message=FALSE}
# I expect to see that the control mean being different than the treatments then the p value will be significant
library(sqldf)
library(dplyr)
library(tidyverse)
library(ggplot2)
data("PlantGrowth")
z<-PlantGrowth
```

# 2 
```{r}
#Data set for normal distribution
ControlData <- filter(z,group=="ctrl")
mean(ControlData$weight)
sd(ControlData$weight)

Treatment1 <- filter(z,group=="trt1")
mean(Treatment1$weight)
sd(Treatment1$weight)

Treatment2 <- filter(z, group=="trt2")
mean(Treatment2$weight)
sd(Treatment2$weight)

```

# 3 
```{r}
#Random data set and data frame
Ctrl <- rnorm(n=10, mean=5.032, sd
                     =0.58)

Trt1 <- rnorm(n=10, mean=4.66, sd
                     =0.79)
Trt2 <- rnorm(n=10, mean=5.526, sd
                     =0.44)
df <- data.frame(Ctrl,Trt1,Trt2, stringsAsFactors = FALSE)

dff <- df %>% pivot_longer(cols=c('Ctrl', 'Trt1', 'Trt2'),names_to='Treatment',values_to='Weight') 

```

# 4  
```{r}
#Anova and graph
original.aov <- aov(Weight ~ Treatment, data = dff)
summary(original.aov)

ggplot(dff, aes(x = Treatment, y = Weight)) +
  geom_boxplot()

```

# 5 
```{r}
#Same Parameters, different numbers
Ctrl <- rnorm(n=10, mean=5.032, sd
                     =0.58)

Trt1 <- rnorm(n=10, mean=4.66, sd
                     =0.79)
Trt2 <- rnorm(n=10, mean=5.526, sd
                     =0.44)
df <- data.frame(Ctrl,Trt1,Trt2, stringsAsFactors = FALSE)

dff <- df %>% pivot_longer(cols=c('Ctrl', 'Trt1', 'Trt2'),names_to='Treatment',values_to='Weight') 

original.aov <- aov(Weight ~ Treatment, data = dff)
summary(original.aov)

ggplot(dff, aes(x = Treatment, y = Weight)) +
  geom_boxplot()
```


# 6 
```{r}
#Adjusting Means
Ctrl <- rnorm(n=10, mean=1.032, sd
              =0.58)

Trt1 <- rnorm(n=10, mean=1.66, sd
              =0.79)
Trt2 <- rnorm(n=10, mean=1.526, sd
              =0.44)
df <- data.frame(Ctrl,Trt1,Trt2, stringsAsFactors = FALSE)

dff2 <- df %>% pivot_longer(cols=c('Ctrl', 'Trt1', 'Trt2'),names_to='Treatment',values_to='Weight') 

aov2 <- aov(Weight ~ Treatment, data = dff2)
summary(aov2)


```

# 7 & 8
The way this dataset is set up it is always significant no matter what I change the sample sizes to. So instead I adjusted the means and found that the only time the p value was not significant was when all the means are similar. 